/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  safelist: [
    // Ensure all design system colors are always generated
    // (some are used via dynamic class construction)
    'text-primary', 'bg-primary', 'border-primary',
    'text-secondary', 'bg-secondary', 'border-secondary',
    'text-tertiary', 'bg-tertiary', 'border-tertiary',
    'text-on-surface', 'bg-on-surface',
    'text-on-surface-variant', 'bg-on-surface-variant',
    'text-error', 'bg-error',
    'bg-surface-container', 'bg-surface-container-low', 'bg-surface-container-high',
    'bg-surface-container-highest', 'bg-surface-container-lowest',
    'text-outline', 'border-outline-variant',
    'text-tertiary-container', 'border-tertiary-container/30',
    'border-tertiary/50', 'border-on-surface-variant/30',
    'text-on-surface-variant/60', 'text-on-surface-variant/40',
    'bg-tertiary/10', 'bg-secondary/10', 'bg-primary/10', 'bg-primary/5',
    'border-primary/20', 'border-secondary/20', 'border-outline-variant/20',
    'border-outline-variant/10', 'border-outline-variant/30',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#d0bcff',
        'primary-container': '#a078ff',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#d0bcff',
        'on-primary': '#3c0091',
        'on-primary-container': '#340080',
        'on-primary-fixed': '#23005c',
        'on-primary-fixed-variant': '#5516be',
        'inverse-primary': '#6d3bd7',

        secondary: '#44e2cd',
        'secondary-container': '#03c6b2',
        'secondary-fixed': '#62fae3',
        'secondary-fixed-dim': '#3cddc7',
        'on-secondary': '#003731',
        'on-secondary-container': '#004d44',
        'on-secondary-fixed': '#00201c',
        'on-secondary-fixed-variant': '#005047',

        tertiary: '#ffb869',
        'tertiary-container': '#ca801e',
        'tertiary-fixed': '#ffdcbb',
        'tertiary-fixed-dim': '#ffb869',
        'on-tertiary': '#482900',
        'on-tertiary-container': '#3f2300',
        'on-tertiary-fixed': '#2c1700',
        'on-tertiary-fixed-variant': '#673d00',

        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',

        background: '#121315',
        'on-background': '#e3e2e5',
        surface: '#121315',
        'surface-dim': '#121315',
        'surface-bright': '#38393b',
        'surface-container-lowest': '#0d0e10',
        'surface-container-low': '#1b1c1e',
        'surface-container': '#1f2022',
        'surface-container-high': '#292a2c',
        'surface-container-highest': '#343537',
        'surface-variant': '#343537',
        'surface-tint': '#d0bcff',

        'on-surface': '#e3e2e5',
        'on-surface-variant': '#cbc3d7',
        'inverse-surface': '#e3e2e5',
        'inverse-on-surface': '#303033',
        outline: '#958ea0',
        'outline-variant': '#494454',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['Inter', 'sans-serif'],
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'score-fill': 'scoreFill 1.5s ease-out forwards',
        'fade-in': 'fadeIn 0.3s ease-out forwards',
        'slide-up': 'slideUp 0.5s ease-out forwards',
      },
      keyframes: {
        scoreFill: {
          '0%': { strokeDashoffset: '440' },
          '100%': { strokeDashoffset: 'var(--score-offset)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
